### ISSUE TITLE
AvecMonDoc: new platform

### ISSUE THREAD

**Issue by gaelbenoit** [CovidTrackerFr/vitemadose-ios#110]
We will add a new platform on back-end, can you please add the support for it?

"plateforme": "AvecMonDoc"

https://patient.avecmondoc.com/assets/images/fronts/logo-AMD.png

**Comment by gaelbenoit** [comment]
the new platform is in production:

![image](https://user-images.githubusercontent.com/11502741/118599777-5b5ed200-b7b0-11eb-8909-713aca2336ee.png)

**Comment by CorentiOS** [comment]
Done #117
