### ISSUE TITLE
Better API Service

### ISSUE THREAD

**Issue by victor-sarda** [CovidTrackerFr/vitemadose-ios#14]
We'll need to refactor the current API Service and/or use a library if needed.
The current one could benefit some improvements, especially around the error handling part.

**Comment by NathanFallet** [comment]
If you want a simple swift package for API querying, you can use [APIRequest.swift](https://github.com/GroupeMINASTE/APIRequest.swift), it's very quick to get started with and easy to use, and it handles most http errors.
