### ISSUE TITLE
[Feature] Add bimedoc platform

### ISSUE THREAD

**Issue by pylapp** [CovidTrackerFr/vitemadose-ios#145]
**Is your feature request related to a problem? Please describe.**

As displayed in the [in-dev web front](https://dev.vitemado.se/dose-rappel/), the Bimedoc platform is not yet managed.

**Describe the solution you'd like**

Manage this platform.

**Describe alternatives you've considered**

_Nope_

**Additional context**

_Nothing_

**Comment by CorentiOS** [comment]
#133
