### ISSUE TITLE
App language is set to English on the App Store

### ISSUE THREAD

**Issue by sudoloic** [CovidTrackerFr/vitemadose-ios#57]
Not sure if it is the right place to tell you this but FYI the app language is set to English on the App Store product page. 

![Capture d’écran 2021-04-22 à 15 26 02](https://user-images.githubusercontent.com/9462401/115722348-3331ae00-a37f-11eb-973c-71c7f1c910a9.png)

**Comment by PlugNPush** [comment]
The change is already pending in #56 :)

**Comment by sudoloic** [comment]
oops sorry I should've looked at the PRs before posting. Nice :)
