### ISSUE TITLE
Add missing analytics

### ISSUE THREAD

**Issue by NathanFallet** [CovidTrackerFr/vitemadose-ios#60]

**Comment by PlugNPush** [comment]
What are those?

**Comment by DavidLibeau** [comment]
Which analytics are you planning to use and why?

**Comment by DavidLibeau** [comment]
It seems that Firebase is already in place : https://github.com/CovidTrackerFr/vitemadose-ios/commit/4f3f65541f6faa3f616e0294d225bb051310ec21

I am proposing to remove all tracking systems in order to respect users' privacy. These analytics are not required for the app to run.

**Comment by NathanFallet** [comment]
See with @victor-sarda for analytics, I think he is already working on it
