### ISSUE TITLE
Rebuild the user interface programmatically

### ISSUE THREAD

**Issue by NathanFallet** [CovidTrackerFr/vitemadose-ios#7]
It could be a great improvement to replace storyboard files by programmatic user interface, mainly about performances. 

Some files are very simple (like the home view which is a navigation controller containing a table view controller), and the loading of those storyboard files takes a lot of time compared of what it would be using programmatic user interface.

**Comment by PlugNCS** [comment]
I'm considering doing this if my Mac has enough power to launch Xcode ^^
