### ISSUE TITLE
Open URL directly instead of using a Safari view controller

### ISSUE THREAD

**Issue by NathanFallet** [CovidTrackerFr/vitemadose-ios#76]
https://github.com/CovidTrackerFr/vitemadose-ios/blob/24e1ef5cce7d47070118cdbf886991e9522e7e90/ViteMaDose/Views/CentresList/CentresListViewController.swift#L64

Opening the URL directly here would allow to open the app of the website if installed.
Also, I thing it's way more comfortable to browse it in safari than in a view controller in the app.

See this conversation:
![image](https://user-images.githubusercontent.com/30439790/115992909-628b2980-a5d0-11eb-85a0-ca9d7bbd891f.png)

**Comment by PlugNPush** [comment]
Are you sure that an SFSafariViewController prevents App Links to operate?

**Comment by PlugNPush** [comment]
@NathanFallet it seems like the URL used for Doctolib is partners.doctolib.fr, which is not declared for App Links. To be verified, but this wouldn't have any effect on the UX.
