### ISSUE TITLE
Changer "doses disponibles" en "créneaux disponibles"

### ISSUE THREAD

**Issue by BrunoSpy** [CovidTrackerFr/vitemadose-ios#88]
Objectif : être cohérent avec la version web et éviter les ambiguïtés.

**Comment by victor-sarda** [comment]
Bonjour, c'est deja fait :) (https://github.com/CovidTrackerFr/vitemadose-ios/pull/73)
La release sera déployée d'ici quelques heures !

Lien vers la beta publique: https://testflight.apple.com/join/MmZt79CX

**Comment by BrunoSpy** [comment]
Guillaume vient de me le dire en effet :)

**Comment by victor-sarda** [comment]
👏
